In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Advertising.csv")

In [3]:
X = df.drop('sales',axis = 1)

In [4]:
y = df['sales']

In [5]:
from sklearn.preprocessing import PolynomialFeatures

In [6]:
polynomial_convertor = PolynomialFeatures(degree=3,include_bias=False)

In [7]:
poly_features = polynomial_convertor.fit_transform(X)

In [8]:
poly_features.shape

(200, 19)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=42)

In [11]:
X_train.shape

(140, 19)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler = StandardScaler()

In [14]:
scaler.fit(X_train)

StandardScaler()

In [15]:
X_train = scaler.transform(X_train)

In [16]:
X_test = scaler.transform(X_test)

In [17]:
X_train[0]

array([ 1.53003874, -0.8862929 , -1.16598019,  1.93705409, -0.22476356,
       -0.62651363, -0.90793157, -0.850692  , -0.81317305,  2.23096225,
        0.10749852, -0.35876444, -0.61820397, -0.60530328, -0.5751799 ,
       -0.81381745, -0.72447935, -0.64260728, -0.56741817])

In [18]:
# poly_features[0]

In [19]:
X_test[0]

array([ 0.08266439,  0.55371878,  1.08861066, -0.18749269,  0.42213484,
        0.79788593,  0.32285459,  0.96554739,  0.89655537, -0.36600988,
        0.09130711,  0.33874113,  0.27095882,  0.75045097,  0.6485836 ,
        0.10170039,  0.63526601,  0.77891369,  0.58997769])

## Ridge Regression / L1 Rgularization


In [20]:
from sklearn.linear_model import Ridge

In [21]:
ridge_model = Ridge(alpha=10)

In [22]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [23]:
test_predictions = ridge_model.predict(X_test)

In [24]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [25]:
MAE = mean_absolute_error(y_test,test_predictions)

In [26]:
MAE

0.6296591346758597

In [27]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [28]:
print(RMSE)

0.8916327541710873


In [29]:
from sklearn.linear_model import RidgeCV

In [30]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0),scoring='neg_mean_absolute_error')

In [31]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(scoring='neg_mean_absolute_error')

In [32]:
ridge_cv_model.alpha_

np.float64(0.1)

In [33]:
#from sklearn.metrics import get_scorer


In [34]:
#get_scorer_names()


In [35]:
test_predictions = ridge_cv_model.predict(X_test)

In [36]:
MAE = mean_absolute_error(y_test,test_predictions)

In [37]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [38]:
MAE

0.46671241131481794

In [39]:
RMSE

np.float64(0.5945136671825971)

In [40]:
ridge_cv_model.coef_

array([ 5.90523815,  0.46316396,  0.68028713, -6.17743395,  3.73671928,
       -1.40708382,  0.00624704,  0.11128917, -0.2617823 ,  2.17135744,
       -0.51480159,  0.70587211,  0.60311504, -0.53271216,  0.5716495 ,
       -0.34685826,  0.36744388, -0.03938079, -0.12192939])

In [41]:
ridge_cv_model.best_score_

-0.3977560291681547

## LASSO -least absolute shrinkage and selection operator

In [42]:
from sklearn.linear_model import LassoCV

In [43]:
lasso_cv_model = LassoCV(eps=0.001,n_alphas = 100,cv = 5, max_iter = 100000) # max_iter = 100000 or eps = 0.001

In [44]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, max_iter=100000)

In [45]:
lasso_cv_model.alpha_

np.float64(0.004924531806474871)

In [54]:
test_predictions = lasso_cv_model.predict(X_test)

In [47]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [48]:
MAE = mean_absolute_error(y_test,test_predictions)

In [49]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [50]:
MAE

0.5123045552899839

In [51]:
RMSE

np.float64(0.6308043049172903)

In [52]:
lasso_cv_model.coef_ # by considering this we can easy to interpret

array([ 5.15048089,  0.4274257 ,  0.29684446, -4.53337994,  3.38937185,
       -0.4288993 ,  0.        ,  0.        ,  0.        ,  1.17891049,
       -0.        ,  0.        ,  0.16706037, -0.        ,  0.        ,
        0.        ,  0.11083672,  0.        ,  0.06155549])

## L1 and L2 Regularization (Elastic Net)

In [55]:
from sklearn.linear_model import ElasticNetCV

In [56]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7, .9, .95, .99, 1],eps=0.001,n_alphas=100,max_iter=1000000)

In [57]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [60]:
elastic_model.l1_ratio_

np.float64(1.0)

In [62]:
elastic_model.alpha_

np.float64(0.004924531806474871)

In [63]:
lasso_cv_model.alpha_

np.float64(0.004924531806474871)

In [64]:
test_predictions = elastic_model.predict(X_test)

In [65]:
MAE = mean_absolute_error(y_test,test_predictions)

In [66]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [67]:
MAE

0.5123045552899839

In [68]:
RMSE

np.float64(0.6308043049172903)