In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../DATA/Advertising.csv')

In [3]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
df.describe()

TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [5]:
X = df.drop('sales',axis = 1)
y = df['sales']

In [6]:
# TRAIN | VALIDATION | HOLD OUT TEST
# 70% | 15% | 15% = 100

# 1st split - 70|30
# 2nnd split - 50|50

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.30, random_state=101)

In [9]:
X_validation, X_holdout_test, y_validation, y_holdout_test = train_test_split(
...     X_test, y_test, test_size=0.5, random_state=101)

In [10]:
len(X)

200

In [11]:
len(X_validation)

30

In [12]:
len(X_holdout_test)

30

# MODEL TRAINING

In [13]:
from sklearn.ensemble import RandomForestRegressor

In [14]:
model = RandomForestRegressor(n_estimators=30,random_state=101)

In [15]:
model.fit(X_train,y_train)

RandomForestRegressor(n_estimators=30, random_state=101)

In [16]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [17]:
validation_predictions = model.predict(X_validation)

In [18]:
validation_predictions

array([14.40333333,  5.47333333,  4.14      , 15.72666667, 11.66666667,
        9.93      , 10.83333333, 11.48      , 18.02      ,  7.60333333,
       10.9       , 21.44333333, 14.08333333,  7.53333333, 11.81333333,
        6.83      , 13.51      , 13.62      , 11.01333333,  7.99666667,
       12.53333333, 21.63      , 19.49      , 15.73      , 16.05666667,
       24.21666667, 20.17666667,  9.50666667, 14.50333333, 19.36333333])

In [19]:
mean_absolute_error(y_validation,validation_predictions)

0.6575555555555552

In [20]:
mean_squared_error(y_validation,validation_predictions)**0.5 #RMSE # STD

0.8542009478215644

In [22]:
df.describe()['sales'] #MAE 0.85 ||RMSE 1.1 --> #0.65 -- 0.85

count    200.000000
mean      14.022500
std        5.217457
min        1.600000
25%       10.375000
50%       12.900000
75%       17.400000
max       27.000000
Name: sales, dtype: float64

In [23]:
## FINAL PERFORMANCE METRICS (HOLDOUT SET)

In [26]:
holdout_predictions = model.predict(X_holdout_test)

In [27]:
mean_absolute_error(y_holdout_test,holdout_prediction)

0.5937777777777775

In [31]:
mean_squared_error(y_holdout_test,holdout_prediction)**0.5

0.745323693040418

In [32]:
final_model = RandomForestRegressor(n_estimators=30,random_state=101)

In [33]:
final_model.fit(X,y)

RandomForestRegressor(n_estimators=30, random_state=101)

In [34]:
import joblib

In [35]:
joblib.dump(final_model,'final_model.pkl')

['final_model.pkl']

In [37]:
list(X.columns)

['TV', 'radio', 'newspaper']

In [38]:
joblib.dump(list(X.columns),'col_names.pkl')

['col_names.pkl']

## LOADING MODEL

In [39]:
new_columns = joblib.load('col_names.pkl')

In [40]:
new_columns

['TV', 'radio', 'newspaper']

In [41]:
loaded_model = joblib.load('final_model.pkl')

In [48]:
input_df = pd.DataFrame([[230.1,37.8,69.2]], columns=new_columns)


In [49]:
loaded_model.predict(input_df)

array([21.99])

In [50]:
input_df = pd.DataFrame([[3000,2,1]], columns=new_columns)
loaded_model.predict(input_df)

array([11.71])