In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
text = ['This is a line',
        'This is another line',
        'Completely different line']

In [3]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer

In [4]:
cv = CountVectorizer()

In [5]:
sparse_matrix = cv.fit_transform(text)

In [6]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]])

In [7]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [8]:
tfidf = TfidfTransformer()

In [9]:
sparse_matrix

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 10 stored elements and shape (3, 6)>

In [11]:
results = tfidf.fit_transform(sparse_matrix) # BOW --> TF-IDF

In [12]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [14]:
tv = TfidfVectorizer()

In [15]:
tv_results = tv.fit_transform(text)

In [18]:
tv_results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])