In [1]:
import numpy as np
print(np.__version__)


2.2.4


In [2]:
import numpy as np
print(np.__version__)


2.2.4


In [3]:
import numpy
print(numpy.__file__)

C:\Users\LENOVO\anaconda3\envs\myenv\lib\site-packages\numpy\__init__.py


In [4]:
import sys
print(sys.path)



['C:\\Users\\LENOVO\\anaconda3\\envs\\myenv\\python310.zip', 'C:\\Users\\LENOVO\\anaconda3\\envs\\myenv\\DLLs', 'C:\\Users\\LENOVO\\anaconda3\\envs\\myenv\\lib', 'C:\\Users\\LENOVO\\anaconda3\\envs\\myenv', '', 'C:\\Users\\LENOVO\\anaconda3\\envs\\myenv\\lib\\site-packages', 'C:\\Users\\LENOVO\\anaconda3\\envs\\myenv\\lib\\site-packages\\win32', 'C:\\Users\\LENOVO\\anaconda3\\envs\\myenv\\lib\\site-packages\\win32\\lib', 'C:\\Users\\LENOVO\\anaconda3\\envs\\myenv\\lib\\site-packages\\Pythonwin']


In [5]:
myl = [1,2,3]
type(myl)

list

In [6]:
my_ar = np.array(myl)

In [7]:
type(my_ar)

numpy.ndarray

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
np.linspace(0,10,90)

array([ 0.        ,  0.11235955,  0.2247191 ,  0.33707865,  0.4494382 ,
        0.56179775,  0.6741573 ,  0.78651685,  0.8988764 ,  1.01123596,
        1.12359551,  1.23595506,  1.34831461,  1.46067416,  1.57303371,
        1.68539326,  1.79775281,  1.91011236,  2.02247191,  2.13483146,
        2.24719101,  2.35955056,  2.47191011,  2.58426966,  2.69662921,
        2.80898876,  2.92134831,  3.03370787,  3.14606742,  3.25842697,
        3.37078652,  3.48314607,  3.59550562,  3.70786517,  3.82022472,
        3.93258427,  4.04494382,  4.15730337,  4.26966292,  4.38202247,
        4.49438202,  4.60674157,  4.71910112,  4.83146067,  4.94382022,
        5.05617978,  5.16853933,  5.28089888,  5.39325843,  5.50561798,
        5.61797753,  5.73033708,  5.84269663,  5.95505618,  6.06741573,
        6.17977528,  6.29213483,  6.40449438,  6.51685393,  6.62921348,
        6.74157303,  6.85393258,  6.96629213,  7.07865169,  7.19101124,
        7.30337079,  7.41573034,  7.52808989,  7.64044944,  7.75

In [13]:
len(np.linspace(0,10,90))

90

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.random.rand()

0.989630304174381

In [16]:
np.random.randn(2,4)

array([[ 0.98140356, -0.20928647,  1.07201909, -0.59060179],
       [-0.62087633,  1.29714846, -0.92627769, -0.82626538]])

In [17]:
np.random.randint(0,101,(4,5))

array([[19, 36, 42,  2, 46],
       [71, 77,  6, 79, 37],
       [73,  6, 89,  1, 88],
       [27,  0, 37,  6, 60]], dtype=int32)

In [18]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [19]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [20]:
arr = np.arange(20)

In [21]:
arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [22]:
ranarr = np.random.randint(0,101,10)
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52], dtype=int32)

In [23]:
ranarr = np.random.randint(0,101,10)
ranarr

array([ 1, 87, 29, 37,  1, 63, 59, 20, 32, 75], dtype=int32)

In [24]:
ranarr.max()

np.int32(87)

In [25]:
ranarr.min()

np.int32(1)

In [26]:
ranarr.argmax()

np.int64(1)

In [27]:
ranarr.argmin()

np.int64(0)

In [28]:
ranarr.dtype

dtype('int32')

In [29]:
arr.shape

(20,)

In [30]:
arr = arr.reshape(1,20)

In [31]:
arr.shape

(1, 20)

In [32]:
arr = np.arange(0,11)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
print(arr[8])

8


In [38]:
arr[1:5]

array([1, 2, 3, 4])

In [41]:
arr[0:5] = 100

In [42]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [43]:
slice_Ar = arr[0:5]

In [44]:
slice_Ar

array([100, 100, 100, 100, 100])

In [45]:
slice_Ar[:] = 99

In [46]:
slice_Ar

array([99, 99, 99, 99, 99])

In [47]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [48]:
arr_c = arr.copy()

In [50]:
arr_c[:] = 100

In [51]:
arr_c

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [52]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [53]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [54]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [55]:
arr_2d.shape

(3, 3)

In [56]:
arr_2d[0]

array([ 5, 10, 15])

In [59]:
arr_2d[1][0]

np.int64(20)

In [60]:
arr_2d[0,2]

np.int64(15)

In [62]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [63]:
arr = np.arange(1,11)

In [64]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [66]:
bool_arr = arr>4

In [67]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [68]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [69]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [70]:
arr + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [71]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [73]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [74]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [75]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [76]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [78]:
1 / arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [79]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [80]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [81]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [82]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr.sum()

np.int64(55)

In [84]:
arr.min()

np.int64(1)

In [85]:
arr.mean()

np.float64(5.5)

In [86]:
arr.max()

np.int64(10)

In [87]:
arr.std()

np.float64(2.8722813232690143)

In [88]:
arr.var()

np.float64(8.25)

In [91]:
arr_2d = np.arange(0,25).reshape(5,5)

In [92]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [93]:
arr_2d.sum()

np.int64(300)

In [94]:
arr_2d.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [95]:
arr_2d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])